[package]
name = "todos"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "todos"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

todos_integrity = { workspace = true } 
